name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7.27.0"
      - name: Build Tina Admin
        id: build-tina-admin
        env:
          CLIENT_ID: "472f0ce5-f1be-459c-785cc9057a1b"
          TINA_TOKEN: "371c01c4f19a9e17eb0ef46917b696d99deb87ae"
        run: |
          yarn
          yarn build
      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: Devwebmichael/devwebmichael.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: Devwebmichael
          user_email: Devwebmichael@gmail.com
          publish_branch: master
        #   cname: example.com
